Traceback (most recent call last):
  File "c:\Users\matth\OneDrive\Documents\Programming Languages Learning\Python Learning\Automate Boring Stuff with Python\12 - Debugging.py", line 26, in <module>
    raise Exception("Error message")
Exception: Error message
Traceback (most recent call last):
  File "c:\Users\matth\OneDrive\Documents\Programming Languages Learning\Python Learning\Automate Boring Stuff with Python\12 - Debugging.py", line 26, in <module>
    raise Exception("Error message")
Exception: Error message
Traceback (most recent call last):
  File "c:\Users\matth\OneDrive\Documents\Programming Languages Learning\Python Learning\Automate Boring Stuff with Python\12 - Debugging.py", line 26, in <module>
    raise Exception("Error message")
Exception: Error message
Traceback (most recent call last):
  File "c:\Users\matth\OneDrive\Documents\Programming Languages Learning\Python Learning\Automate Boring Stuff with Python\12 - Debugging.py", line 26, in <module>
    raise Exception("Error message")
Exception: Error message
Traceback (most recent call last):
  File "c:\Users\matth\OneDrive\Documents\Programming Languages Learning\Python Learning\Automate Boring Stuff with Python\12 - Debugging.py", line 26, in <module>
    raise Exception("Error message")
Exception: Error message
Traceback (most recent call last):
  File "c:\Users\matth\OneDrive\Documents\Programming Languages Learning\Python Learning\Automate Boring Stuff with Python\12 - Debugging.py", line 26, in <module>
    raise Exception("Error message")
Exception: Error message
